language: node_js
node_js:
  - "9"
  - "8"
  - "6"

sudo: required

services:
  - docker

install:
  - docker-compose up -d
  - cd id/ && npm install && cd ..
  - cd spread/ && npm install && cd ..

script:
  - cd id/ && npm test && cd ..
  - cd spread/ && npm test && cd ..
  - docker-compose stop

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    
    docker build -t danielmschmidt/zipkin-playground-id ./id/;
    docker push danielmschmidt/zipkin-playground-id;
    docker build -t danielmschmidt/zipkin-playground-spread ./spread/;
    docker push danielmschmidt/zipkin-playground-spread;
    fi