language: node_js
node_js:
  - "9"
  - "8"
  - "6"

sudo: required

services:
  - docker

install:
  - "pushd id && npm install && popd"
test:
  - "pushd id && npm test && popd"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t danielmschmidt/zipkin-playground-id .;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push danielmschmidt/zipkin-playground-id;
    fi